apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: variables.airflow.drfaust92
spec:
  group: airflow.drfaust92
  scope: Namespaced
  names:
    kind: Variable
    plural: variables
    singular: variable
    shortNames:
      - vars
      - var
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                value:
                  type: string
                  description: The variable value (direct value).
                secretRef:
                  type: object
                  description: Reference to a Kubernetes Secret for the variable value.
                  required:
                    - name
                    - key
                  properties:
                    name:
                      type: string
                      description: The name of the Kubernetes Secret.
                    key:
                      type: string
                      description: The key within the Secret.
                description:
                  type: string
                  description: The variable description.
              oneOf:
                - required:
                    - value
                - required:
                    - secretRef
